var ContentData = {
    "userColumn":6,
    //……你的操作表，规则(role)
    "title":"预付款冲正",
    "items":[{
        "type":"input",
        "label":"主键",
        "column":6,
        "isRequired":true,
        "key":"index",
        "list_show":true,
        "card_show":true,
        "isHidden":true,
        "isPkCode":true,
        "list_hidden_data":true
    },{
        "type":"input",
        "label":"标题",
        "column":6,
        "isRequired":true,
        "key":"title",
        "list_show":true,
        "card_show":true,
        "isHidden":false,
        "isListUrl":true,
        "list_hidden_data":false
    },{
        "type":"select",
        "label":"类型",
        "column":3,
        "isRequired":false,
        "key":"type",
        "dict":"type_dict",
        "default":"dd",
        "list_show":false,
        "card_show":true,
        "isHidden":false,
        "list_hidden_data":false
    },{
        "type":"select",
        "label":"允许",
        "column":3,
        "isRequired":false,
        "key":"yes_no",
        "dict":"exit_type",
        "default":"y",
        "list_show":false,
        "card_show":true,
        "isHidden":false,
        "list_hidden_data":false
    },{
        "type":"radio",
        "label":"是否",
        "column":3,
        "isRequired":false,
        "key":"is_exit",
        "dict":"exit_type",
        "default":"y",
        "list_show":false,
        "card_show":true,
        "isHidden":false,
        "list_hidden_data":false
    },{
        "type":"input",
        "label":"名字",
        "column":3,
        "isRequired":true,
        "key":"name",
        "list_show":true,
        "card_show":true,
        "isHidden":false,
        "list_hidden_data":false
    },{
        "type":"input",
        "label":"年龄",
        "column":3,
        "isRequired":true,
        "key":"age",
        "list_show":true,
        "card_show":true,
        "isHidden":false,
        "list_hidden_data":false
    },{
        "type":"input",
        "label":"地址",
        "column":3,
        "isRequired":true,
        "key":"addre",
        "list_show":true,
        "card_show":true,
        "isHidden":false,
        "list_hidden_data":false
    },{
        "type":"input",
        "label":"金额",
        "column":2,
        "isRequired":false,
        "key":"money",
        "list_show":false,
        "card_show":true,
        "isHidden":false,
        "list_hidden_data":false
    },{
        "type":"input",
        "label":"个数",
        "column":2,
        "isRequired":false,
        "key":"count",
        "list_show":false,
        "card_show":true,
        "isHidden":false,
        "list_hidden_data":false
    },{
        "type":"checkbox",
        "label":"选择类型",
        "column":2,
        "isRequired":false,
        "key":"check_type",
        "dict":"type_dict",
        "default":"dd",
        "list_show":false,
        "card_show":true,
        "isHidden":false,
        "list_hidden_data":true
    },{
        "type":"textarea",
        "label":"备注",
        "column":6,
        "isRequired":false,
        "key":"memo",
        "list_show":false,
        "card_show":true,
        "isHidden":false,
        "list_hidden_data":true
    }],
    "dataList":[{
        "index":"23121231313131323",
        "title":"关于…………的请示---1",
        "name":"张三",
        "age":"24",
        "addre":"河南"
    },{
        "index":"45645654646464646",
        "title":"关于…………的请示---2",
        "name":"李四",
        "age":"25",
        "addre":"河北"
    },{
        "index":"78968975675757576",
        "title":"关于…………的请示---3",
        "name":"王二",
        "age":"26",
        "addre":"北京"
    }],
    "dicts":[{
        "key":"type_dict",
        "values":{
            "dd":"当当",
            "jd":"京东",
            "ymx":"亚马逊"
        }
    },{
        "key":"exit_type",
        "values":{
            "y":"是",
            "n":"否"
        }
    }],
    "buttons":[{
        "key":"add",
        "icon":"plus",
        "value":"新增",
        "type":"list",
        "group":"default"
    },{
        "key":"save",
        "icon":"floppy-disk",
        "value":"保存",
        "type":"card",
        "group":"default"
    },{
        "key":"modify",
        "icon":"remove",
        "value":"关闭",
        "type":"card",
        "group":"default"
    },{
        "key":"modify",
        "icon":"share-alt",
        "value":"撤销",
        "type":"card",
        "group":"default"
    },{
        "key":"modify",
        "icon":"paperclip",
        "value":"附件",
        "type":"card",
        "group":"file"
    },{
        "key":"drop",
        "icon":"minus",
        "value":"删除",
        "type":"list",
        "group":"default"
    },{
        "key":"query",
        "icon":"eye-open",
        "value":"查看",
        "type":"list",
        "group":"search"
    },{
        "key":"download",
        "icon":"inbox",
        "value":"导出",
        "type":"list",
        "group":"exp"
    }]
};
var ContentConfig = {
    "columnsConfig":function(){
        return {
            "getStaticColumns" : function() {
                return 12;
            },
            "getItemsType" : function() {
                return {
                    "input":"input",
                    "select":"select",
                    "radio":"radio",
                    "checkbox":"checkbox",
                    "textarea":"textarea",
                    "button":"button"
                };
            },
            "getButtonGroup":function(){
                return{
                    "default":"default",
                    "search":"search",
                    "exp":"exp",
                    "file":"file",
                    "other":"other"
                }
            },
            "getCardConfig":function(){
                return "card";
            },
            "getListConfig":function() {
                return "list";
            }
        };
    }
};